### ISSUE TITLE
Rename File stopped working

### ISSUE THREAD

**Issue by spudly** [jurassix/atom-javascript-refactor#114] opened 2017-02-28 13:57 UTC
After right-clicking on a file and choosing "Rename (with refactor support)", nothing happens. The dialog box where it asks for the new name does not come up.

This stopped working recently (like a few weeks ago).

No errors in the dev console either 😭

**Comment by jurassix** [comment] 2017-02-28 15:22
@spudly - good to hear from you! Thanks for the report. Which tree-view are you using? Nuclide, other?

@ahutchings - wonder if the refactors to tree broke stephen's tree-view? 

Possible culprit: https://github.com/jurassix/atom-javascript-refactor/commit/b02f844eef9feaa3ed2c82305bbd11e60787237c

**Comment by spudly** [comment] 2017-02-28 17:05
using tree-view (default one)

**Comment by ahutchings** [comment] 2017-03-01 17:40
I don't think this issue is related to the selector refactors - I actually noticed the selector issue while looking into the issue @spudly is describing, and I just confirmed that I can reproduce @spudly's issue with 0.5.5.

In my testing, I found that the PathRenameForm is being rendered, but some other element is immediately gaining focus after rendering, which triggers a `blur` event on the AtomInput component and closes the PathRenameForm. I haven't found the cause of this yet, but I believe it must be related to a change in Atom itself or some other plugin both @spudly and I are using, since it started recently and wasn't due to a change in the javascript-refactor plugin.

The next step would be to debug the focus/blur issue further to find the cause. Then we either file a bug in Atom (if it's a bug), or find some other way to work around it.

**Comment by ahutchings** [comment] 2017-03-02 01:11
This looks like it is related to a change in Atom related to focus management in the built-in `atom-text-editor` component. The FocusEvent raised by https://github.com/atom/atom/commit/6f4a506517a4865686ac17b240476a67003f7cfe causes the PathRenameForm to be closed. The Facebook team updated one of their UI components to work around this issue - https://github.com/facebook/nuclide/commit/60bb34fb2e7c4647ce7c5acd7d671230c584d001#diff-138ef803b94ce8c1ccf059de27ca69bfR263. 

This would probably be best fixed in the `<atom-text-editor />` component. Failing that, Nuclide's `<AtomInput />` component would be second-best (this is even mentioned by the comment in the nuclide comment linked above). We can temporarily work around the issue by replicating the Nuclide patch in our own AtomInput. I will look into this later unless you two beat me to it.

**Closed** 2017-03-02 04:44 UTC
Labels: bug

**Comment by ahutchings** [comment] 2017-03-02 04:53
@spudly I published a fix for that in v0.5.7 that is working for me - give it a try!

**Comment by jurassix** [comment] 2017-03-02 13:54
@ahutchings nice work!

**Comment by spudly** [comment] 2017-03-02 13:59
🎉  Works like a charm. Thanks!
